BOARD = zc706_MIG
UBOOT_CONFIG = zc70x
BOARD_MODEL = xilinx.com:zc706:part0:1.0
PART = xc7z045ffg900-2
# CONFIG is the target configuration for the rocket-chip generator

#TOP_MODULE_PROJECT = zynq
#CONFIG = ZynqFPGAConfig
TOP_MODULE_PROJECT = zynq.boom
CONFIG ?= SmallBoomZynqConfig
#CONFIG ?= MediumBoomZynqConfig

include ../common/Makefrag
